### ISSUE TITLE
功能问题

### ISSUE THREAD

**Issue by Mtr1994** [ArkNX/PSS_ASIO#1]
最近尝试用本框架实现一个局域网通信的程序，发现有几个地方不是很清楚，请教一下：
1、TCP 有没有实现心跳功能，还是说需要自己发包的完成，我在示例中没有找到相关代码。
2、程序在收到 UDP 广播的时候，能正常回复嘛？获取的端口是广播的端口？
3、连接的 ID 会不会耗尽啊， UDP 无连接，如果发错误的数据包，会一直断开再连接，ID 也一直自增，最后会循环嘛 ？

**Comment by freeeyes** [comment]
1.并不是所有的都需要心跳，心跳一般是在客户端发起的。这个部分，你参考我的PSS客户端组件。那里有实现规则。https://github.com/freeeyes/PSS_Client，这个代码不需要第三方程序，head only，支持编译成库。PSS服务器提供定时器，如果你需要定时往客户端发送数据包，参考我的readme。
2. 当然支持回复，当收到广播的时候，会在收到的包里显示来源端口的地址，剩下的你自己处理啦。
3. 链接ID不会耗尽，如果到了尽头，我会从1开始，而且跳过正在使用的ID。目前的ID是int，上线是40亿，没问题。
