### ISSUE TITLE
崩溃问题1

### ISSUE THREAD

**Issue by yukuilong** [ArkNX/PSS_ASIO#3]
![1680277543346](https://user-images.githubusercontent.com/3782998/229168344-c95e1fa6-f9e3-4b6e-aee7-e8c096ab9141.jpg)

**Comment by yukuilong** [comment]
现在有1k 多个设备频繁的访问服务器 ，这个崩溃现在几分钟就出现，找到了一个这个不知道是不是这个原因导致的
![image](https://user-images.githubusercontent.com/3782998/229168716-f81a969d-f973-4af4-8e47-5920188ad76d.png)

**Comment by freeeyes** [comment]
这个问题，我好好查查，你是在什么情况下出这个问题的？是在插件里试图关闭socket造成的吗？

**Comment by freeeyes** [comment]
> 现在有1k 多个设备频繁的访问服务器 ，这个崩溃现在几分钟就出现，找到了一个这个不知道是不是这个原因导致的 ![image](https://user-images.githubusercontent.com/3782998/229168716-f81a969d-f973-4af4-8e47-5920188ad76d.png)

你是在插件里关闭socket的时候造成的吗？

**Comment by yukuilong** [comment]
我换成最新的代码后这问题没有在出现了
