### ISSUE TITLE
换成最新版本后还是偶现崩溃

### ISSUE THREAD

**Issue by yukuilong** [ArkNX/PSS_ASIO#5]
崩溃1
![1680691210560](https://user-images.githubusercontent.com/3782998/230057536-1c7b408a-9371-4846-9c2c-4b9803eb2c96.jpg)
崩溃2
![1680691285447](https://user-images.githubusercontent.com/3782998/230057796-0b58c2af-e703-4ce5-9e33-e881c87f3060.jpg)

而且我发现连接和断开连接回调里的计数会出现问题，代码如下：_connectNum 数会变成很大的数字，应该是_connectNum-- 到负数了,感觉是Disconnect消息发多了。
![image](https://user-images.githubusercontent.com/3782998/230058532-dd1ec2bc-e6be-40af-9969-d704f1390e75.png)
![1680691344231](https://user-images.githubusercontent.com/3782998/230058604-ceddc365-2cb0-4dc1-b852-082670549ace.jpg)

**Comment by freeeyes** [comment]
你加我的QQ说吧，我有一个技术讨论群。

540961187













在 2023-04-05 18:51:13，"SunShine" ***@***.***> 写道：

崩溃1

崩溃2


而且我发现连接和断开连接回调里的计数会出现问题，代码如下：_connectNum 数会变成很大的数字，应该是_connectNum-- 到负数了

**Comment by freeeyes** [comment]
> 崩溃1 ![1680691210560](https://user-images.githubusercontent.com/3782998/230057536-1c7b408a-9371-4846-9c2c-4b9803eb2c96.jpg) 崩溃2 ![1680691285447](https://user-images.githubusercontent.com/3782998/230057796-0b58c2af-e703-4ce5-9e33-e881c87f3060.jpg)
> 
> 而且我发现连接和断开连接回调里的计数会出现问题，代码如下：_connectNum 数会变成很大的数字，应该是_connectNum-- 到负数了,感觉是Disconnect消息发多了。 ![image](https://user-images.githubusercontent.com/3782998/230058532-dd1ec2bc-e6be-40af-9969-d704f1390e75.png) ![1680691344231](https://user-images.githubusercontent.com/3782998/230058604-ceddc365-2cb0-4dc1-b852-082670549ace.jpg)

你加我们的QQ讨论组吧。
540961187
我看看这个问题。

**Comment by freeeyes** [comment]
> 崩溃1 ![1680691210560](https://user-images.githubusercontent.com/3782998/230057536-1c7b408a-9371-4846-9c2c-4b9803eb2c96.jpg) 崩溃2 ![1680691285447](https://user-images.githubusercontent.com/3782998/230057796-0b58c2af-e703-4ce5-9e33-e881c87f3060.jpg)
> 
> 而且我发现连接和断开连接回调里的计数会出现问题，代码如下：_connectNum 数会变成很大的数字，应该是_connectNum-- 到负数了,感觉是Disconnect消息发多了。 ![image](https://user-images.githubusercontent.com/3782998/230058532-dd1ec2bc-e6be-40af-9969-d704f1390e75.png) ![1680691344231](https://user-images.githubusercontent.com/3782998/230058604-ceddc365-2cb0-4dc1-b852-082670549ace.jpg)

首先，baseCommand是多线程调用的，是否是线程安全的，取决于你配置的工作线程数量，如果是多线程，对应的函数有两种处理办法，第一是加锁，第二是入消息队列，然后后续自己处理。取决于你的逻辑是否允许对多线程的并行需求。比如你这个计数器，你在配置工程的时候设置了3个工作线程，你就需要对此进行加锁或入队列。

**Comment by freeeyes** [comment]
已解决，业务代码自己的问题。
